# Generated by Django 5.2.2 on 2025-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tblUsuarios',
            },
        ),
    ]
