# Generated by Django 5.2.2 on 2025-06-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPuntoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('x0', models.FloatField()),
                ('n_iteraciones', models.IntegerField()),
                ('decimales', models.IntegerField()),
                ('error_final', models.FloatField()),
                ('resultado_final', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.miusuario')),
            ],
            options={
                'db_table': 'historial_puntofijo',
            },
        ),
        migrations.CreateModel(
            name='Iteracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_iteracion', models.IntegerField()),
                ('x_anterior', models.FloatField()),
                ('x_nueva', models.FloatField()),
                ('error', models.FloatField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteraciones', to='usuario.historialpuntofijo')),
            ],
            options={
                'db_table': 'iteraciones',
                'ordering': ['numero_iteracion'],
            },
        ),
    ]
