# Generated by Django 5.2.2 on 2025-06-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteracion',
            options={},
        ),
        migrations.AlterModelTable(
            name='iteracion',
            table='tblIteraciones',
        ),
    ]
