# Generated by Django 5.2.2 on 2025-06-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_iteracion_options_alter_iteracion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialpuntofijo',
            table='tblHistorialPuntoFijo',
        ),
        migrations.AlterModelTable(
            name='iteracion',
            table='tblIteracionesPuntoFijo',
        ),
    ]
