# Generated by Django 5.2.2 on 2025-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_historialpuntofijo_table_alter_iteracion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpuntofijo',
            name='error_Calculado',
            field=models.FloatField(default=0.0),
        ),
    ]
