# Generated by Django 5.2.2 on 2025-06-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('usuario', '0004_historialpuntofijo_error_calculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMetodo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=255)),
                ('AreaI', models.FloatField()),
                ('AreaT', models.FloatField()),
                ('AreaTC', models.FloatField()),
                ('errorT', models.FloatField()),
                ('errorTC', models.FloatField()),
                ('n_espacios', models.IntegerField()),
                ('decimales', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.miusuario')),
            ],
            options={
                'db_table': 'tblHistorialMetodo2',
            },
        ),
        migrations.CreateModel(
            name='ValoresMetodo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorF', models.FloatField()),
                ('valorH', models.FloatField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='usuario.historialmetodo2')),
            ],
            options={
                'db_table': 'tblValoresMetodo2',
            },
        ),
    ]
