# Generated by Django 5.2.2 on 2025-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_historialpuntofijo_error_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracion',
            name='error',
            field=models.FloatField(null=True),
        ),
    ]
