# Generated by Django 5.2.2 on 2025-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_iteracion_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpuntofijo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_punto_fijo/'),
        ),
    ]
